In [1]:
import pickle
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
pwd

'/Users/sanju/Documents/DS/Generative AI/NLP/bank_exit_pred__using_DL_Project/reserach'

In [3]:
import os 
os.chdir("..")

In [4]:
pwd

'/Users/sanju/Documents/DS/Generative AI/NLP/bank_exit_pred__using_DL_Project'

In [5]:
with open("artifacts/model.pkl","rb") as file:
    model=pickle.load(file)

In [6]:
model

<Sequential name=sequential, built=True>

In [7]:
with open("artifacts/preprocessor.pkl","rb") as file:
    preprocssor=pickle.load(file)

In [8]:
preprocssor

ColumnTransformer(transformers=[('num_features', StandardScaler(),
                                 Index(['CreditScore', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary'],
      dtype='object')),
                                ('cat_features', OneHotEncoder(),
                                 Index(['Geography', 'Gender'], dtype='object'))])

In [9]:
data=pd.read_csv("data/Churn_Modelling.csv")
data.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [10]:
df=data.drop(["RowNumber","CustomerId","Surname"],axis=1)

In [11]:
df.head(1)

CreditScore Geography  Gender  Age  Tenure  Balance  NumOfProducts  \
0          619    France  Female   42       2      0.0              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1

In [12]:
df.shape

(10000, 11)

In [13]:
# Define features (X) and target (y)
# X = df.drop(columns=['Exited'])  # Independent variables
# y = df['Exited']  # Target variable

# # Perform train-test split (80% train, 20% test)
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [14]:
df.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0  
2          1               0        113931.57       1  
3          0               0         93826.63       0  
4          1               1         79084.10       0

In [15]:
d1=df.head(1).drop("Exited",axis=1)

In [16]:
d1

CreditScore Geography  Gender  Age  Tenure  Balance  NumOfProducts  \
0          619    France  Female   42       2      0.0              1   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1        101348.88

In [17]:
transformed_d1=preprocssor.transform(d1)

In [18]:
transformed_d1

array([[-0.33880827,  0.29493847, -1.04241787, -1.21847056, -0.91668767,
         0.64920267,  0.97481699,  0.01595384,  1.        ,  0.        ,
         0.        ,  1.        ,  0.        ]])

In [19]:
d1_pred=model.predict(transformed_d1)
d1_pred

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step


array([[0.23583212]], dtype=float32)

In [20]:
def pred_output(pred):
    if pred<0.5:
        return 0
    else:
        return 1

In [21]:
pred_output(d1_pred)

0

In [22]:
df[1:2]

CreditScore Geography  Gender  Age  Tenure   Balance  NumOfProducts  \
1          608     Spain  Female   41       1  83807.86              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
1          0               1        112542.58       0

In [23]:
d2=df[1:2].drop("Exited",axis=1)

In [24]:
transformed_d2=preprocssor.transform(d2)

In [25]:
pred_output(model.predict(transformed_d2))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step


0

In [26]:
model.predict(transformed_d2)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step


array([[0.23150398]], dtype=float32)